### ISSUE TITLE
1612615-Đào Việt Thắng

### ISSUE THREAD

**Issue by thang-dao** [beohoang98/CS_DataScience_Project#1]
Mình có những góp ý như sau:
-Data: mình thấy trong bảng data các bạn crawl về có rất nhiều ô thiếu dữ liệu, các bạn có hướng xử lý chưa? Trong bảng có rất nhiều cột (feature), bạn dự định dùng những cột nào sử dụng cho bài toán?
-Bài toán các bạn đặt ra giống như bài toán matching để chọn sản phẩm nào phù hợp với người dùng nào nhất, vậy cách thông thường là chỉ cần sắp xếp theo chí người khác hàng đưa vào rồi tìm kiếm trong bảng dữ liệu theo thông tin đó để chọn ra sản phẩm phù hợp. Các bạn cần dùng machine learning ở đây để làm gì? có tối ưu hơn không?

**Comment by beohoang98** [comment]
Ok, cảm ơn bạn đã góp ý :+1: 
1. Hiện tại nhóm mình crawl dữ liệu chưa đầy đủ và cũng chưa biết yếu tố nào quyết định để filter lại nên vẫn để raw data như vậy
2. Ý tưởng của nhóm mình khác matching là có thêm 1 yếu tố là dựa vào input là thông tin cá nhân từ khách hàng (nghề nghiệp + giới tính, ...) để tăng sự phù hợp của sản phẩm hơn. Hiện tại nhóm mình chưa hiện thực ý tưởng này
